name: Build and Push Image

on:
    push:
        branches: [main]

jobs:
    build:
        #runs-on: [self-hosted, Linux]
        runs-on: [ubuntu-24.04-arm]

        steps:
            - name: Checkout Source Code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GHCR_PAT }}

            - name: Build and Push Image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: dockerfile
                  push: true
                  tags: ghcr.io/${{ github.repository_owner }}/blog-backend:latest
                  # platforms: linux/arm64
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
